INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('0', '1', 'Calgary', 'Calgary Stampede', '1168509', '2015');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('1', '6', 'UNKNOWN', 'FIFA World Cup', '3178856', '2010');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('2', '5', 'UNKNOWN', 'FIFA World Cup', '5029873', '2014');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('3', '2', 'Chicago', 'UNKNOWN', NULL, '2015');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('4', '8', 'UNKNOWN', 'Africa Cup of Nations', NULL, '2006');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('5', '1', 'Toronto', 'UNKNOWN', NULL, '2015');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('6', '1', 'UNKNOWN', 'IIHF World U20 Championship', '325138', '2006');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('7', '8', 'SharmelSheikh', '2005 Sharm el-Sheikh attacks', NULL, '2005');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('8', '9', 'Delhi', '29 October 2005 Delhi bombings', NULL, '2005');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('9', '1', 'UNKNOWN', 'UNKNOWN', '1195299', '2007');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('10', '9', 'Varanasi', '2006 Varanasi bombings', NULL, '2006');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('11', '9', 'Bangalore', 'Under The Peepal Tree (UTPT)', NULL, '2015');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('12', '9', 'Mumbai', '11 July 2006 Mumbai train bombings', NULL, '2006');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('13', '6', 'UNKNOWN', 'Africa Cup of Nations', '729000', '2013');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('14', '9', 'Malegaon', '2006 blasts at Malegaon', NULL, '2006');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('15', '4', 'UNKNOWN', 'World Women''s Handball Championship', NULL, '2009');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('16', '9', 'UNKNOWN', 'AFC Youth Championship', '51050', '2006');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('17', '9', 'WestBengal', '2006 West Bengal train disaster', NULL, '2006');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('18', '9', 'UNKNOWN', 'AFC Challenge Cup', '15900', '2008');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('19', '5', 'UNKNOWN', 'UNKNOWN', '292161', '2008');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('20', '2', 'Musayyib', '2005 Musayyib bombing', NULL, '2012');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('21', '9', 'Panipat', 'Samjhauta Express bombings', NULL, '2007');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('22', '4', 'UNKNOWN', 'IIHF World Championship Division I', '51436', '2007');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('23', '7', 'UNKNOWN', 'UNKNOWN', NULL, '2005');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('24', '1', 'UNKNOWN', 'UNKNOWN', '477040', '2008');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('25', '9', 'Hyderabad', 'Mecca Masjid Bombing

{{Location map', NULL, '2007');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('26', '9', 'DiggiPalace', 'Jaipur Literature Festival', NULL, '2015');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('27', '9', 'UNKNOWN', 'ONGC Nehru Cup', NULL, '2007');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('28', '9', 'Agra', 'UNKNOWN', NULL, '2013');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('29', '7', 'Karachi', '2007 Karsaz attack', NULL, '2007');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('30', '9', 'Kanpur', 'Techkriti', '250001000', '2015');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('31', '5', 'UNKNOWN', 'FIFA Confederations Cup', '804659', '2013');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('32', '7', 'LiaquatNationalBagh', 'Benazir Bhutto assassination', NULL, '2007');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('33', '1', 'UNKNOWN', 'IIHF U20 World Championships', '455342', '2012');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('34', '9', 'NewDelhi', 'Eastwind', NULL, '2008');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('35', '7', 'Charsadda', '2008 Charsadda bombing', NULL, '2008');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('36', '4', 'Parachinar', '2008 Parachinar bombing', NULL, '2008');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('37', '9', 'EmbassyofIndia', '2008 Indian Embassy bombing in Kabul', NULL, '2008');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('38', '9', 'Bangalore', '2008 Bangalore serial blasts', NULL, '2008');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('39', '9', 'Ahmedabad', 'Death toll in Ahmedabad serial blasts rises to 55', NULL, '2008');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('40', '7', 'WahCantonment', '2008 Wah bombing', NULL, '2008');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('41', '7', 'Swat', '23 August 2008 Swat Valley bombing', NULL, '2008');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('42', '9', 'Delhi', '13 September 2008 Delhi bombings', NULL, '2008');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('43', '6', 'Krugersdorp', 'Nic Diederichs Technical High School slashing', NULL, '2008');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('44', '7', 'Islamabad', 'Islamabad Marriott Hotel bombing', NULL, '2008');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('45', '2', 'Jerusalem', '2008 Jerusalem BMW attack', NULL, '2008');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('46', '9', 'Delhi', '27 September 2008 Delhi blast', NULL, '2008');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('47', '9', 'MaharashtraandGujarat', '29 September 2008 Western India bombings', NULL, '2008');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('48', '7', 'OrakzaiAgency', '10 October 2008 Orakzai bombing', NULL, '2008');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('49', '9', 'Imphal', '21 October 2008 Imphal bombings', NULL, '2008');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('50', '9', 'Assam', '2008 Assam serial blasts', NULL, '2008');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('51', '7', 'Peshawar', 'December 2008 Peshawar bombing', NULL, '2008');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('52', '9', 'Guwahati', '2009 Guwahati serial blasts', NULL, '2009');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('53', '9', 'Srinagar', '2006 Srinagar bombings', NULL, '2006');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('54', '8', 'KhanelKhalili', 'Khan el-Khalili bombing', NULL, '2009');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('55', '7', 'Lahore', '2009 attack on the Sri Lanka national cricket team in Pakistan', NULL, '2011');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('56', '7', 'Lahore', 'Lahore police academy attack, 2009', NULL, '2009');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('57', '7', 'Chakwal', '5 April 2009 Chakwal Mosque attack', NULL, '2009');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('58', '7', 'Karachi', 'Operation Clean-up', NULL, '2015');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('59', '9', 'Assam', '2009 Assam serial blasts', NULL, '2009');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('60', '7', 'Lahore', '2009 Lahore bombing', NULL, '2009');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('61', '7', 'Peshawar', 'Pearl Continental hotel bombing', NULL, '2009');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('62', '5', 'UNKNOWN', 'Grand Prix de Futsal', NULL, '2006');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('63', '7', 'Makin', '2009 Makin airstrike', NULL, '2009');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('64', '9', 'Chitrakootvillage', '2009 Chitrakoot Shootout', NULL, '2009');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('65', '7', 'MianChannu', 'Mian Channu school house bombing', NULL, '2009');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('66', '5', 'UNKNOWN', 'Grand Prix de Futsal', NULL, '2009');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('67', '1', 'UNKNOWN', 'UNKNOWN', NULL, '2010');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('68', '9', 'UNKNOWN', 'ONGC Nehru Cup', NULL, '2009');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('69', '9', 'EmbassyofIndia', '2009 Kabul Indian embassy attack', NULL, '2009');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('70', '7', 'Islamabad', '2009 International Islamic University bombing', NULL, '2009');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('71', '8', 'AlAyyat', 'Al Ayyat train collision', NULL, '2009');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('72', '8', 'UNKNOWN', 'DR Congo}}', NULL, '2010');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('73', '7', 'Peshawar', '28 October 2009 Peshawar Market Bombing', NULL, '2009');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('74', '9', 'KeyesGirlsHighSchool', 'Kalasagaram Annual Cultural Festival Of Music, Dance and Drama', NULL, '2009');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('75', '5', 'UNKNOWN', 'World Women''s Handball Championship', '65750', '2011');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('76', '7', 'Karachi', '2009 Karachi bombing', NULL, '2009');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('77', '8', 'NagHammadi', 'Nag Hammadi Massacre', NULL, '2010');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('78', '9', 'GermanBakery', '2010 Pune bombing

{{Location map', NULL, '2010');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('79', '8', 'UNKNOWN', 'African Championship', NULL, '2010');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('80', '3', 'UNKNOWN', 'CONCACAF Women''s Championship', NULL, '2010');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('81', '9', 'UNKNOWN', '15th Census of the India', NULL, '2010');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('82', '4', 'UNKNOWN', 'Asia-Oceania Korfball Championship', NULL, '2010');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('83', '9', 'Dantewada', 'April 2010 Maoist attack in Dantewada', NULL, '2010');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('84', '9', 'Bangalore', 'Unmaad', '30000400', '2016');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('85', '7', 'Peshawar', '2010 Peshawar bombing', NULL, '2010');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('86', '6', 'Johannesburg', 'African Youth Championship', NULL, '2011');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('87', '2', 'Pontiac', 'Green Soccer Bowl', NULL, '2010');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('88', '1', 'Toronto', '2010 G-20 Toronto summit', NULL, '2010');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('89', '1', 'UNKNOWN', 'Canada Cup', NULL, '2009');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('90', '2', 'Columbia', 'Roots N Blues N BBQ Festival', NULL, '2013');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('91', '4', 'Fuzhou', 'Fuzhou derailment', NULL, '2010');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('92', '3', 'UNKNOWN', 'IIHF World Championship Division III', NULL, '2005');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('93', '1', 'UNKNOWN', 'Canada Cup', NULL, '2010');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('94', '7', 'MohmandAgency', 'Mohmand Agency attack', NULL, '2010');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('95', '9', 'Sainthia', 'Sainthia train collision', NULL, '2010');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('96', '4', 'NanjingNoPlasticsfactoryabandonedQixiaDistrict', '2010 Nanjing chemical plant explosion', NULL, '2010');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('97', '7', 'Karachi', '2010 Karachi riots', NULL, '2010');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('98', '4', 'Aksu', '2010 Aksu bombing', NULL, '2010');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('99', '7', 'Lahore', 'September 2010 Lahore bombings', NULL, '2010');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('100', '7', 'Quetta', 'September 2010 Quetta bombing', NULL, '2010');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('101', '7', 'MandiBahauddin', '2005 Mandi Bahauddin attacks', NULL, '2005');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('102', '7', 'DarraAdamKhel', '2010 Darra Adam Khel mosque bombing', NULL, '2010');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('103', '6', 'UNKNOWN', 'IIHF World Championship Division III', NULL, '2011');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('104', '9', 'UNKNOWN', '[[List of Chief Ministers of Bihar', NULL, '2010');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('105', '1', 'UNKNOWN', 'FIFA Women''s World Cup', '2725860', '2015');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('106', '9', 'Varanasi', '2010 Varanasi bombing', NULL, '2010');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('107', '7', 'Ghalanai', 'December 2010 Mohmand Agency bombings', NULL, '2010');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('108', '9', 'Ajmer', 'Ajmer Sharif Dargah blast', NULL, '2007');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('109', '6', 'UNKNOWN', 'African Nations Championship', '296440', '2014');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('110', '7', 'Faisalabad', '2011 Faisalabad bombing', NULL, '2011');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('111', '7', 'Peshawar', '9 March 2011 Peshawar bombing', NULL, '2011');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('112', '2', 'Jerusalem', '2011 Jerusalem bus stop bombing', NULL, '2011');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('113', '1', 'DownsviewParkToronto', 'Heavy T.O.', NULL, '2012');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('114', '1', 'UNKNOWN', '[[Prime Minister of Canada', NULL, '2015');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('115', '8', 'Imbaba', '2011 Imbaba church attacks', NULL, '2011');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('116', '7', 'CharsaddaDistrict', '2011 Charsadda bombing', NULL, '2011');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('117', '3', 'Mexico', '2011 Mexican Fire Season', NULL, '2011');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('118', '1', 'UNKNOWN', 'UNKNOWN', NULL, '2007');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('119', '3', 'ArizonaNewMexico', 'Wallow Fire', NULL, '2011');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('120', '3', 'NewMexico', 'Las Conchas Fire', NULL, '2011');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('121', '7', 'Karachi', 'Jul & Aug 2011 Karachi target killings', NULL, '2011');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('122', '4', 'Kashgar', '2011 Kashgar attacks', NULL, '2011');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('123', '9', 'Agra', '2011 Agra bombing', NULL, '2011');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('124', '3', 'CuidadJuarez', 'Murder of Luis Carlos Santiago', NULL, '2010');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('125', '1', 'UNKNOWN', 'IIHF World Junior Championship', '366370', '2015');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('126', '5', 'UNKNOWN', 'Pan American Handball Men''s Youth Championship', NULL, '2010');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('127', '5', 'UNKNOWN', 'Pan American Handball Women''s Youth Championship', NULL, '2006');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('128', '5', 'UNKNOWN', 'Pan American Handball Women''s Youth Championship', NULL, '2007');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('129', '5', 'UNKNOWN', 'Pan American Handball Women''s Youth Championship', NULL, '2008');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('130', '9', 'Kozhikode', 'UNKNOWN', NULL, '2012');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('131', '4', 'UNKNOWN', 'UNKNOWN', NULL, '2012');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('132', '7', 'KohistanDistrict', 'February 2012 Kohistan Shia massacre', NULL, '2012');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('133', '7', 'Peshawar', 'The trials of tribal journalists', NULL, '2011');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('134', '6', 'Durban', '5th BRICS Summit', NULL, '2013');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('135', '5', 'UNKNOWN', 'Pan American Handball Men''s Youth Championship', NULL, '2006');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('136', '3', 'AtizapndeZaragoza', 'Monterrey Tech bombing', NULL, '2011');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('137', '3', 'NuevoLaredo', '2012 Nuevo Laredo massacres', NULL, '2012');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('138', '6', 'CapeTown', 'Cape Town International Challenge', NULL, '2012');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('139', '6', 'UNKNOWN', 'IIHF World Championship Division III', NULL, '2013');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('140', '9', 'MChinnaswamyStadiumBangalore', '2010 Bangalore stadium bombing', NULL, '2010');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('141', '3', 'GilaNationalForest', 'Whitewater-Baldy Complex Fire', NULL, '2012');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('142', '9', 'Penukonda', 'Penukonda train collision', NULL, '2012');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('143', '2', 'ZionSquare', 'Zion Square lynching', NULL, '2012');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('144', '1', 'Montreal', '2012 Montreal shooting', NULL, '2012');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('145', '9', 'Kochi', 'Emerging Kerala', NULL, '2012');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('146', '3', 'BocaDelRo', '2012 Veracruz murder of journalists', NULL, '2012');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('147', '6', 'UNKNOWN', 'SAIHA Senior Club Championship', NULL, '2012');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('148', '3', 'MexicoCity', 'Homeless World Cup', NULL, '2012');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('149', '7', 'BachaKhanInternationalAirport', '2012 Pakistan airport attack', NULL, '2012');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('150', '5', 'UNKNOWN', 'Torneio Internacional Cidade de SÃ£o Paulo de Futebol Feminino', NULL, '2011');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('151', '5', 'UNKNOWN', 'Torneio Internacional Cidade de SÃ£o Paulo de Futebol Feminino', NULL, '2010');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('152', '5', 'UNKNOWN', 'Torneio Internacional Cidade de SÃ£o Paulo de Futebol Feminino', NULL, '2009');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('153', '1', 'UNKNOWN', 'IIHF World Junior Championship', NULL, '2017');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('154', '4', 'Yongchuan', 'Four Nations Tournament', NULL, '2013');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('155', '8', 'GizaGovernorate', 'Badrashin railway accident', NULL, '2013');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('156', '9', 'Dilsukhnagar', '2013 Hyderabad bombings', NULL, '2013');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('157', '9', 'Malleswaram', '2013 Bangalore blast', NULL, '2013');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('158', '1', 'Quebec', '2013 VIA Rail Canada terrorism plot', NULL, '2012');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('159', '9', 'WestLafayette', '2008 NCAA Division I Men''s Golf Championship', NULL, '2008');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('160', '7', 'Pakistan', '2013 Pakistan election day bombings', NULL, '2013');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('161', '7', 'Quetta', 'June 2013 Quetta attacks', NULL, '2013');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('162', '9', 'Srinagar', 'June 2013 Srinagar attack', NULL, '2013');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('163', '6', 'UNKNOWN', 'SAIHA Junior Interprovincial Championship', NULL, '2013');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('164', '1', 'Sydney', 'World U-17 Hockey Challenge', NULL, '2014');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('165', '8', 'Cairo', 'August 2013 Cairo sit-ins dispersal', NULL, '2013');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('166', '7', 'UNKNOWN', 'SAFF Women''s Championship', NULL, '2014');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('167', '7', 'Peshawar', 'Peshawar church attack', NULL, '2013');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('168', '9', 'Chennai', 'UNKNOWN', NULL, '2013');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('169', '5', 'UNKNOWN', 'Grand Prix de Futsal', NULL, '2013');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('170', '9', 'PatnaJunctionMultiplelocationsatGandhiMaidanMarg', '''''2013 Patna Serial Blasts''''', NULL, '2013');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('171', '1', 'UNKNOWN', 'UNKNOWN', NULL, '2013');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('172', '7', 'MastungDistrict', '2014 Mastung bus bombing', NULL, '2014');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('173', '3', 'UNKNOWN', 'Pan American Ice Hockey Tournament', NULL, '2014');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('174', '7', 'Islamabad', 'Islamabad court attack', NULL, '2014');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('175', '9', 'ChennaiCentralrailwaystation', 'Train Bombing', NULL, '2014');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('176', '4', 'rmqi', 'April 2014 ÃrÃ¼mqi attack', NULL, '2014');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('177', '4', 'Guangzhou', '2014 Guangzhou attack', NULL, '2014');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('178', '4', 'GongyuanStreet', 'May 2014 ÃrÃ¼mqi attack', NULL, '2014');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('179', '9', 'Bangalore', 'India Inclusion Summit', NULL, '2013');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('180', '1', 'NorthwestTerritories', '2014 Northwest Territories fires', NULL, '2014');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('181', '7', 'Gujranwala', '2014 Gujranwala attacks', NULL, '2014');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('182', '4', 'KunshanZhongrongMetalProductsCo', '2014 Kunshan explosion', NULL, '2014');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('183', '2', 'Shuafat', 'Kidnapping and murder of Mohammed Abu Khdeir', NULL, '2014');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('184', '1', 'UNKNOWN', '[[International Champions Cup]]', NULL, '2015');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('185', '1', 'UNKNOWN', 'Ball Hockey World Championship', NULL, '2015');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('186', '1', 'Ottawa', '2015 Ottawa Larmond twins terror conspiracy', NULL, '2014');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('187', '2', 'UNKNOWN', 'CONCACAF Men''s Olympic Qualifying Championship', NULL, '2015');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('188', '2', 'UNKNOWN', 'UNKNOWN', NULL, '2015');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('189', '5', 'Americana', 'Pan- American Korfball Championship', NULL, '2014');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('190', '7', 'Lahore', '2015 Lahore church bombings  {{URDU', NULL, '2015');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('191', '6', 'CapeTown', 'UNKNOWN', NULL, '2015');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('192', '5', 'UNKNOWN', 'Pan American Men''s Club Handball Championship', NULL, '2014');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('193', '4', 'RepublicsofKhakassiaandZabaykalskyKrai', '2015 Russian wildfires<!--This must be the same name as the article. Do not change unless the article is moved.-->', NULL, '2015');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('194', '6', 'DurbanJohannesburgSouthAfrica', 'Durban Xenophobic attack 2015', NULL, '2015');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('195', '6', 'Denverstation', 'Denver train crash', NULL, '2015');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('196', '1', 'UNKNOWN', 'IIHF World Championship', NULL, '2016');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('197', '3', 'UNKNOWN', 'Pan American Ice Hockey Tournament', NULL, '2015');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('198', '2', 'Newport', 'UNKNOWN', NULL, '2016');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('199', '4', 'Xiamen', 'World University Football Cup', NULL, '2015');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('200', '9', 'Srinagar', 'UNKNOWN', NULL, '2015');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('201', '2', 'Jerusalem', 'Lions'' Gate stabbing', NULL, '2015');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('202', '3', 'UNKNOWN', 'IIHF U20 World Championship Division III', NULL, '2016');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('203', '9', 'NationalCapitalRegionIndia', '<!-- Title to display, if other than page name -->', NULL, '2016');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('204', '7', 'Jhelum', 'Ahmadi place of worship set ablaze in Jhelum, riots erupt after blasphemy allegations', NULL, '2015');
INSERT INTO "Event" (event_key, event_location_country, specific_location, name, attendance, date) VALUES ('205', '9', 'Chennai', 'UNKNOWN', NULL, '2016');
