INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("0", "Canada", "Calgary", "Calgary Stampede", "11685092015", "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("1", "South Africa", "UNKNOWN", "FIFA World Cup", "3178856", "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("2", "Brazil", "UNKNOWN", "FIFA World Cup", "5029873", "2014");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("3", "USA", "Chicago", "UNKNOWN", "UNKNOWN", "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("4", "Egypt", "UNKNOWN", "Africa Cup of Nations", "0", "2006");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("5", "Canada", "Toronto", "UNKNOWN", "UNKNOWN", "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("6", "Canada", "UNKNOWN", "IIHF World U20 Championship", "325138", "2006");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("7", "Egypt", "SharmelSheikh", "2005 Sharm el-Sheikh attacks", "UNKNOWN", "2005");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("8", "India", "Delhi", "29 October 2005 Delhi bombings", "UNKNOWN", "2005");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("9", "Canada", "UNKNOWN", "UNKNOWN", "1195299", "2007");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("10", "India", "Varanasi", "2006 Varanasi bombings", "UNKNOWN", "2006");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("11", "India", "Bangalore", "Under The Peepal Tree (UTPT)", "UNKNOWN", "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("12", "India", "Mumbai", "11 July 2006 Mumbai train bombings", "UNKNOWN", "2006");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("13", "South Africa", "UNKNOWN", "Africa Cup of Nations", "729000", "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("14", "India", "Malegaon", "2006 blasts at Malegaon", "UNKNOWN", "2006");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("15", "China", "UNKNOWN", "World Women's Handball Championship", "0", "2009");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("16", "India", "UNKNOWN", "AFC Youth Championship", "51050", "2006");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("17", "India", "WestBengal", "2006 West Bengal train disaster", "UNKNOWN", "2006");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("18", "India", "UNKNOWN", "AFC Challenge Cup", "15900", "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("19", "Brazil", "UNKNOWN", "UNKNOWN", "292161", "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("20", "USA", "Musayyib", "2005 Musayyib bombing", "UNKNOWN", "2012");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("21", "India", "Panipat", "Samjhauta Express bombings", "UNKNOWN", "2007");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("22", "China", "UNKNOWN", "IIHF World Championship Division I", "51436", "2007");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("23", "Pakistan", "UNKNOWN", "UNKNOWN", "0", "2005");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("24", "Canada", "UNKNOWN", "UNKNOWN", "477040", "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("25", "India", "Hyderabad", "Mecca Masjid Bombing
{{Location map", "UNKNOWN", "2007");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("26", "India", "DiggiPalace", "Jaipur Literature Festival", "UNKNOWN", "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("27", "India", "UNKNOWN", "ONGC Nehru Cup", "0", "2007");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("28", "India", "Agra", "UNKNOWN", "UNKNOWN", "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("29", "Pakistan", "Karachi", "2007 Karsaz attack", "UNKNOWN", "2007");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("30", "India", "Kanpur", "Techkriti", "250001000", "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("31", "Brazil", "UNKNOWN", "FIFA Confederations Cup", "804659", "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("32", "Pakistan", "LiaquatNationalBagh", "Benazir Bhutto assassination", "UNKNOWN", "2007");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("33", "Canada", "UNKNOWN", "IIHF U20 World Championships", "455342", "2012");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("34", "India", "NewDelhi", "Eastwind", "UNKNOWN", "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("35", "Pakistan", "Charsadda", "2008 Charsadda bombing", "UNKNOWN", "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("36", "China", "Parachinar", "2008 Parachinar bombing", "UNKNOWN", "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("37", "India", "EmbassyofIndia", "2008 Indian Embassy bombing in Kabul", "UNKNOWN", "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("38", "India", "Bangalore", "2008 Bangalore serial blasts", "UNKNOWN", "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("39", "India", "Ahmedabad", "Death toll in Ahmedabad serial blasts rises to 55", "UNKNOWN", "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("40", "Pakistan", "WahCantonment", "2008 Wah bombing", "UNKNOWN", "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("41", "Pakistan", "Swat", "23 August 2008 Swat Valley bombing", "UNKNOWN", "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("42", "India", "Delhi", "13 September 2008 Delhi bombings", "UNKNOWN", "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("43", "South Africa", "Krugersdorp", "Nic Diederichs Technical High School slashing", "UNKNOWN", "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("44", "Pakistan", "Islamabad", "Islamabad Marriott Hotel bombing", "UNKNOWN", "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("45", "USA", "Jerusalem", "2008 Jerusalem BMW attack", "UNKNOWN", "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("46", "India", "Delhi", "27 September 2008 Delhi blast", "UNKNOWN", "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("47", "India", "MaharashtraandGujarat", "29 September 2008 Western India bombings", "UNKNOWN", "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("48", "Pakistan", "OrakzaiAgency", "10 October 2008 Orakzai bombing", "UNKNOWN", "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("49", "India", "Imphal", "21 October 2008 Imphal bombings", "UNKNOWN", "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("50", "India", "Assam", "2008 Assam serial blasts", "UNKNOWN", "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("51", "Pakistan", "Peshawar", "December 2008 Peshawar bombing", "UNKNOWN", "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("52", "India", "Guwahati", "2009 Guwahati serial blasts", "UNKNOWN", "2009");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("53", "India", "Srinagar", "2006 Srinagar bombings", "UNKNOWN", "2006");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("54", "Egypt", "KhanelKhalili", "Khan el-Khalili bombing", "UNKNOWN", "2009");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("55", "Pakistan", "Lahore", "2009 attack on the Sri Lanka national cricket team in Pakistan", "UNKNOWN", "2011");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("56", "Pakistan", "Lahore", "Lahore police academy attack, 2009", "UNKNOWN", "2009");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("57", "Pakistan", "Chakwal", "5 April 2009 Chakwal Mosque attack", "UNKNOWN", "2009");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("58", "Pakistan", "Karachi", "Operation Clean-up", "UNKNOWN", "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("59", "India", "Assam", "2009 Assam serial blasts", "UNKNOWN", "2009");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("60", "Pakistan", "Lahore", "2009 Lahore bombing", "UNKNOWN", "2009");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("61", "Pakistan", "Peshawar", "Pearl Continental hotel bombing", "UNKNOWN", "2009");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("62", "Brazil", "UNKNOWN", "Grand Prix de Futsal", "0", "2006");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("63", "Pakistan", "Makin", "2009 Makin airstrike", "UNKNOWN", "2009");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("64", "India", "Chitrakootvillage", "2009 Chitrakoot Shootout", "UNKNOWN", "2009");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("65", "Pakistan", "MianChannu", "Mian Channu school house bombing", "UNKNOWN", "2009");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("66", "Brazil", "UNKNOWN", "Grand Prix de Futsal", "0", "2009");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("67", "Canada", "UNKNOWN", "UNKNOWN", "UNKNOWN", "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("68", "India", "UNKNOWN", "ONGC Nehru Cup", "0", "2009");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("69", "India", "EmbassyofIndia", "2009 Kabul Indian embassy attack", "UNKNOWN", "2009");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("70", "Pakistan", "Islamabad", "2009 International Islamic University bombing", "UNKNOWN", "2009");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("71", "Egypt", "AlAyyat", "Al Ayyat train collision", "UNKNOWN", "2009");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("72", "Egypt", "UNKNOWN", "DR Congo}}", "0", "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("73", "Pakistan", "Peshawar", "28 October 2009 Peshawar Market Bombing", "UNKNOWN", "2009");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("74", "India", "KeyesGirlsHighSchool", "Kalasagaram Annual Cultural Festival Of Music, Dance and Drama", "UNKNOWN", "2009");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("75", "Brazil", "UNKNOWN", "World Women's Handball Championship", "65750", "2011");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("76", "Pakistan", "Karachi", "2009 Karachi bombing", "UNKNOWN", "2009");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("77", "Egypt", "NagHammadi", "Nag Hammadi Massacre", "UNKNOWN", "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("78", "India", "GermanBakery", "2010 Pune bombing
{{Location map", "UNKNOWN", "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("79", "Egypt", "UNKNOWN", "African Championship", "0", "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("80", "Mexico", "UNKNOWN", "CONCACAF Women's Championship", "UNKNOWN", "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("81", "India", "UNKNOWN", "15th Census of the India", "UNKNOWN", "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("82", "China", "UNKNOWN", "Asia-Oceania Korfball Championship", "0", "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("83", "India", "Dantewada", "April 2010 Maoist attack in Dantewada", "UNKNOWN", "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("84", "India", "Bangalore", "Unmaad", "30000400", "2016");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("85", "Pakistan", "Peshawar", "2010 Peshawar bombing", "UNKNOWN", "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("86", "South Africa", "Johannesburg", "African Youth Championship", "0", "2011");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("87", "USA", "Pontiac", "Green Soccer Bowl", "0", "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("88", "Canada", "Toronto", "2010 G-20 Toronto summit", "UNKNOWN", "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("89", "Canada", "UNKNOWN", "Canada Cup", "UNKNOWN", "2009");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("90", "USA", "Columbia", "Roots N Blues N BBQ Festival", "UNKNOWN", "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("91", "China", "Fuzhou", "Fuzhou derailment", "UNKNOWN", "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("92", "Mexico", "UNKNOWN", "IIHF World Championship Division III", "UNKNOWN", "2005");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("93", "Canada", "UNKNOWN", "Canada Cup", "UNKNOWN", "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("94", "Pakistan", "MohmandAgency", "Mohmand Agency attack", "UNKNOWN", "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("95", "India", "Sainthia", "Sainthia train collision", "UNKNOWN", "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("96", "China", "NanjingNoPlasticsfactoryabandonedQixiaDistrict", "2010 Nanjing chemical plant explosion", "UNKNOWN", "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("97", "Pakistan", "Karachi", "2010 Karachi riots", "UNKNOWN", "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("98", "China", "Aksu", "2010 Aksu bombing", "UNKNOWN", "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("99", "Pakistan", "Lahore", "September 2010 Lahore bombings", "UNKNOWN", "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("100", "Pakistan", "Quetta", "September 2010 Quetta bombing", "UNKNOWN", "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("101", "Pakistan", "MandiBahauddin", "2005 Mandi Bahauddin attacks", "UNKNOWN", "2005");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("102", "Pakistan", "DarraAdamKhel", "2010 Darra Adam Khel mosque bombing", "UNKNOWN", "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("103", "South Africa", "UNKNOWN", "IIHF World Championship Division III", "UNKNOWN", "2011");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("104", "India", "UNKNOWN", "[[List of Chief Ministers of Bihar", "UNKNOWN", "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("105", "Canada", "UNKNOWN", "FIFA Women's World Cup", "2725860", "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("106", "India", "Varanasi", "2010 Varanasi bombing", "UNKNOWN", "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("107", "Pakistan", "Ghalanai", "December 2010 Mohmand Agency bombings", "UNKNOWN", "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("108", "India", "Ajmer", "Ajmer Sharif Dargah blast", "UNKNOWN", "2007");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("109", "South Africa", "UNKNOWN", "African Nations Championship", "296440", "2014");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("110", "Pakistan", "Faisalabad", "2011 Faisalabad bombing", "UNKNOWN", "2011");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("111", "Pakistan", "Peshawar", "9 March 2011 Peshawar bombing", "UNKNOWN", "2011");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("112", "USA", "Jerusalem", "2011 Jerusalem bus stop bombing", "UNKNOWN", "2011");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("113", "Canada", "DownsviewParkToronto", "Heavy T.O.", "UNKNOWN", "2012");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("114", "Canada", "UNKNOWN", "[[Prime Minister of Canada", "UNKNOWN", "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("115", "Egypt", "Imbaba", "2011 Imbaba church attacks", "UNKNOWN", "2011");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("116", "Pakistan", "CharsaddaDistrict", "2011 Charsadda bombing", "UNKNOWN", "2011");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("117", "Mexico", "Mexico", "2011 Mexican Fire Season", "UNKNOWN", "2011");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("118", "Canada", "UNKNOWN", "UNKNOWN", "0", "2007");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("119", "Mexico", "ArizonaNewMexico", "Wallow Fire", "UNKNOWN", "2011");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("120", "Mexico", "NewMexico", "Las Conchas Fire", "UNKNOWN", "2011");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("121", "Pakistan", "Karachi", "Jul & Aug 2011 Karachi target killings", "UNKNOWN", "2011");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("122", "China", "Kashgar", "2011 Kashgar attacks", "UNKNOWN", "2011");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("123", "India", "Agra", "2011 Agra bombing", "UNKNOWN", "2011");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("124", "Mexico", "CuidadJuarez", "Murder of Luis Carlos Santiago", "UNKNOWN", "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("125", "Canada", "UNKNOWN", "IIHF World Junior Championship", "366370", "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("126", "Brazil", "UNKNOWN", "Pan American Handball Men's Youth Championship", "0", "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("127", "Brazil", "UNKNOWN", "Pan American Handball Women's Youth Championship", "0", "2006");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("128", "Brazil", "UNKNOWN", "Pan American Handball Women's Youth Championship", "0", "2007");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("129", "Brazil", "UNKNOWN", "Pan American Handball Women's Youth Championship", "0", "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("130", "India", "Kozhikode", "UNKNOWN", "UNKNOWN", "2012");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("131", "China", "UNKNOWN", "UNKNOWN", "UNKNOWN", "2012");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("132", "Pakistan", "KohistanDistrict", "February 2012 Kohistan Shia massacre", "UNKNOWN", "2012");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("133", "Pakistan", "Peshawar", "The trials of tribal journalists", "UNKNOWN", "2011");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("134", "South Africa", "Durban", "5th BRICS Summit", "UNKNOWN", "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("135", "Brazil", "UNKNOWN", "Pan American Handball Men's Youth Championship", "0", "2006");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("136", "Mexico", "AtizapndeZaragoza", "Monterrey Tech bombing", "UNKNOWN", "2011");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("137", "Mexico", "NuevoLaredo", "2012 Nuevo Laredo massacres", "UNKNOWN", "2012");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("138", "South Africa", "CapeTown", "Cape Town International Challenge", "0", "2012");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("139", "South Africa", "UNKNOWN", "IIHF World Championship Division III", "UNKNOWN", "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("140", "India", "MChinnaswamyStadiumBangalore", "2010 Bangalore stadium bombing", "UNKNOWN", "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("141", "Mexico", "GilaNationalForest", "Whitewater-Baldy Complex Fire", "UNKNOWN", "2012");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("142", "India", "Penukonda", "Penukonda train collision", "UNKNOWN", "2012");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("143", "USA", "ZionSquare", "Zion Square lynching", "UNKNOWN", "2012");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("144", "Canada", "Montreal", "2012 Montreal shooting", "UNKNOWN", "2012");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("145", "India", "Kochi", "Emerging Kerala", "UNKNOWN", "2012");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("146", "Mexico", "BocaDelRo", "2012 Veracruz murder of journalists", "UNKNOWN", "2012");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("147", "South Africa", "UNKNOWN", "SAIHA Senior Club Championship", "0", "2012");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("148", "Mexico", "MexicoCity", "Homeless World Cup", "0", "2012");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("149", "Pakistan", "BachaKhanInternationalAirport", "2012 Pakistan airport attack", "UNKNOWN", "2012");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("150", "Brazil", "UNKNOWN", "Torneio Internacional Cidade de SÃ£o Paulo de Futebol Feminino", "0", "2011");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("151", "Brazil", "UNKNOWN", "Torneio Internacional Cidade de SÃ£o Paulo de Futebol Feminino", "0", "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("152", "Brazil", "UNKNOWN", "Torneio Internacional Cidade de SÃ£o Paulo de Futebol Feminino", "0", "2009");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("153", "Canada", "UNKNOWN", "IIHF World Junior Championship", "0", "2017");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("154", "China", "Yongchuan", "Four Nations Tournament", "0", "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("155", "Egypt", "GizaGovernorate", "Badrashin railway accident", "UNKNOWN", "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("156", "India", "Dilsukhnagar", "2013 Hyderabad bombings", "UNKNOWN", "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("157", "India", "Malleswaram", "2013 Bangalore blast", "UNKNOWN", "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("158", "Canada", "Quebec", "2013 VIA Rail Canada terrorism plot", "UNKNOWN", "2012");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("159", "India", "WestLafayette", "2008 NCAA Division I Men's Golf Championship", "UNKNOWN", "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("160", "Pakistan", "Pakistan", "2013 Pakistan election day bombings", "UNKNOWN", "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("161", "Pakistan", "Quetta", "June 2013 Quetta attacks", "UNKNOWN", "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("162", "India", "Srinagar", "June 2013 Srinagar attack", "UNKNOWN", "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("163", "South Africa", "UNKNOWN", "SAIHA Junior Interprovincial Championship", "0", "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("164", "Canada", "Sydney", "World U-17 Hockey Challenge", "0", "2014");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("165", "Egypt", "Cairo", "August 2013 Cairo sit-ins dispersal", "UNKNOWN", "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("166", "Pakistan", "UNKNOWN", "SAFF Women's Championship", "0", "2014");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("167", "Pakistan", "Peshawar", "Peshawar church attack", "UNKNOWN", "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("168", "India", "Chennai", "UNKNOWN", "UNKNOWN", "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("169", "Brazil", "UNKNOWN", "Grand Prix de Futsal", "UNKNOWN", "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("170", "India", "PatnaJunctionMultiplelocationsatGandhiMaidanMarg", "''2013 Patna Serial Blasts''", "UNKNOWN", "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("171", "Canada", "UNKNOWN", "UNKNOWN", "0", "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("172", "Pakistan", "MastungDistrict", "2014 Mastung bus bombing", "UNKNOWN", "2014");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("173", "Mexico", "UNKNOWN", "Pan American Ice Hockey Tournament", "0", "2014");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("174", "Pakistan", "Islamabad", "Islamabad court attack", "UNKNOWN", "2014");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("175", "India", "ChennaiCentralrailwaystation", "Train Bombing", "UNKNOWN", "2014");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("176", "China", "rmqi", "April 2014 ÃrÃ¼mqi attack", "UNKNOWN", "2014");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("177", "China", "Guangzhou", "2014 Guangzhou attack", "UNKNOWN", "2014");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("178", "China", "GongyuanStreet", "May 2014 ÃrÃ¼mqi attack", "UNKNOWN", "2014");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("179", "India", "Bangalore", "India Inclusion Summit", "UNKNOWN", "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("180", "Canada", "NorthwestTerritories", "2014 Northwest Territories fires", "UNKNOWN", "2014");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("181", "Pakistan", "Gujranwala", "2014 Gujranwala attacks", "UNKNOWN", "2014");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("182", "China", "KunshanZhongrongMetalProductsCo", "2014 Kunshan explosion", "UNKNOWN", "2014");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("183", "USA", "Shuafat", "Kidnapping and murder of Mohammed Abu Khdeir", "UNKNOWN", "2014");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("184", "Canada", "UNKNOWN", "[[International Champions Cup]]", "0", "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("185", "Canada", "UNKNOWN", "Ball Hockey World Championship", "0", "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("186", "Canada", "Ottawa", "2015 Ottawa Larmond twins terror conspiracy", "UNKNOWN", "2014");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("187", "USA", "UNKNOWN", "CONCACAF Men's Olympic Qualifying Championship", "0", "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("188", "USA", "UNKNOWN", "UNKNOWN", "0", "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("189", "Brazil", "Americana", "Pan- American Korfball Championship", "0", "2014");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("190", "Pakistan", "Lahore", "2015 Lahore church bombings  {{URDU", "UNKNOWN", "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("191", "South Africa", "CapeTown", "UNKNOWN", "UNKNOWN", "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("192", "Brazil", "UNKNOWN", "Pan American Men's Club Handball Championship", "0", "2014");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("193", "China", "RepublicsofKhakassiaandZabaykalskyKrai", "2015 Russian wildfires<!--This must be the same name as the article. Do not change unless the article is moved.-->", "UNKNOWN", "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("194", "South Africa", "DurbanJohannesburgSouthAfrica", "Durban Xenophobic attack 2015", "UNKNOWN", "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("195", "South Africa", "Denverstation", "Denver train crash", "UNKNOWN", "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("196", "Canada", "UNKNOWN", "IIHF World Championship", "0", "2016");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("197", "Mexico", "UNKNOWN", "Pan American Ice Hockey Tournament", "0", "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("198", "USA", "Newport", "UNKNOWN", "UNKNOWN", "2016");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("199", "China", "Xiamen", "World University Football Cup", "0", "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("200", "India", "Srinagar", "UNKNOWN", "UNKNOWN", "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("201", "USA", "Jerusalem", "Lions' Gate stabbing", "UNKNOWN", "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("202", "Mexico", "UNKNOWN", "IIHF U20 World Championship Division III", "UNKNOWN", "2016");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("203", "India", "NationalCapitalRegionIndia", "<!-- Title to display, if other than page name -->", "UNKNOWN", "2016");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("204", "Pakistan", "Jhelum", "Ahmadi place of worship set ablaze in Jhelum, riots erupt after blasphemy allegations", "UNKNOWN", "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("205", "India", "Chennai", "UNKNOWN", "UNKNOWN", "2016");
