INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("0", "Canada", "[[Calgary]]", "Calgary Stampede", NULL, "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("1", "South Africa", "9", "FIFA World Cup", NULL, "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("2", "Brazil", "12", "FIFA World Cup", NULL, "2014");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("3", "USA", "[[Chicago]]", NULL, NULL, "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("4", "Egypt", "4", "Africa Cup of Nations", NULL, "2006");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("5", "Canada", "[[Toronto]]", NULL, NULL, "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("6", "Canada", "3", "IIHF World U20 Championship", NULL, "2006");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("7", "Egypt", "[[Sharm el-Sheikh]]", "2005 Sharm el-Sheikh attacks", NULL, "2005");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("8", "India", "Delhi", "29 October 2005 Delhi bombings", NULL, "2005");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("9", "Canada", "6", NULL, NULL, "2007");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("10", "India", "[[Varanasi]]", "2006 Varanasi bombings", NULL, "2006");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("11", "India", "[[Bangalore]]", "Under The Peepal Tree (UTPT)", NULL, "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("12", "India", "[[Mumbai]]", "11 July 2006 Mumbai train bombings", NULL, "2006");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("13", "South Africa", "5", "Africa Cup of Nations", NULL, "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("14", "India", "[[Malegaon]]", "2006 blasts at Malegaon", NULL, "2006");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("15", "China", "6", "World Women's Handball Championship", NULL, "2009");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("16", "India", "2", "AFC Youth Championship", NULL, "2006");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("17", "India", "[[West Bengal]]", "2006 West Bengal train disaster", NULL, "2006");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("18", "India", "2", "AFC Challenge Cup", NULL, "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("19", "Brazil", "2", "", NULL, "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("20", "India", "Panipat", "Samjhauta Express bombings", NULL, "2007");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("21", "China", NULL, "IIHF World Championship Division I", NULL, "2007");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("22", "Canada", "2", "", NULL, "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("23", "India", "[[Hyderabad", "Mecca Masjid Bombing
{{Location map", NULL, "2007");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("24", "India", "[[Diggi Palace]]", "Jaipur Literature Festival", NULL, "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("25", "India", "1", "ONGC Nehru Cup", NULL, "2007");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("26", "India", "[[Agra]]", NULL, NULL, "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("27", "India", "[[Kanpur", "Techkriti", NULL, "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("28", "Brazil", "6", "FIFA Confederations Cup", NULL, "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("29", "Canada", "2", "IIHF U20 World Championships", NULL, "2012");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("30", "India", "[[New Delhi", "Eastwind", NULL, "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("31", "India", "Embassy of India", "2008 Indian Embassy bombing in Kabul", NULL, "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("32", "India", "[[Bangalore]]", "2008 Bangalore serial blasts", NULL, "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("33", "India", "[[Ahmedabad]]", "Death toll in Ahmedabad serial blasts rises to 55", NULL, "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("34", "India", "[[Delhi]]", "13 September 2008 Delhi bombings", NULL, "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("35", "South Africa", "[[Krugersdorp]]", "Nic Diederichs Technical High School slashing", NULL, "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("36", "India", "[[Delhi]]", "27 September 2008 Delhi blast", NULL, "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("37", "India", "[[Maharashtra]] and [[Gujarat]]", "29 September 2008 Western India bombings", NULL, "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("38", "India", "[[Imphal]]", "21 October 2008 Imphal bombings", NULL, "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("39", "India", "[[Assam]]", "2008 Assam serial blasts", NULL, "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("40", "India", "[[Guwahati]]", "2009 Guwahati serial blasts", NULL, "2009");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("41", "India", "[[Srinagar]]", "2006 Srinagar bombings", NULL, "2006");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("42", "Egypt", "[[Khan el-Khalili]]", "Khan el-Khalili bombing", NULL, "2009");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("43", "India", "[[Assam]]", "2009 Assam serial blasts", NULL, "2009");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("44", "Brazil", "1", "Grand Prix de Futsal", NULL, "2006");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("45", "India", "Chitrakoot village", "2009 Chitrakoot Shootout", NULL, "2009");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("46", "Brazil", "2", "Grand Prix de Futsal", NULL, "2009");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("47", "Canada", "1", NULL, NULL, "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("48", "India", "1", "ONGC Nehru Cup", NULL, "2009");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("49", "India", "Embassy of India", "2009 Kabul Indian embassy attack", NULL, "2009");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("50", "Egypt", "Al Ayyat", "Al Ayyat train collision", NULL, "2009");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("51", "Egypt", "2", "DR Congo}}", NULL, "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("52", "India", "[[Keyes Girls High School]]", "Kalasagaram Annual Cultural Festival Of Music, Dance and Drama", NULL, "2009");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("53", "Brazil", "4", "World Women's Handball Championship", NULL, "2011");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("54", "Egypt", "[[Nag Hammadi]]", "Nag Hammadi Massacre", NULL, "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("55", "India", "German Bakery", "2010 Pune bombing
{{Location map", NULL, "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("56", "Egypt", "2", "African Championship", NULL, "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("57", "Mexico", "1", "CONCACAF Women's Championship", NULL, "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("58", "India", NULL, "15th Census of the India", NULL, "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("59", "China", "", "Asia-Oceania Korfball Championship", NULL, "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("60", "India", "[[Dantewada]]", "April 2010 Maoist attack in Dantewada", NULL, "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("61", "India", "[[Bangalore", "Unmaad", NULL, "2016");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("62", "South Africa", "[[Johannesburg]]", "African Youth Championship", NULL, "2011");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("63", "USA", "[[Pontiac]]", "Green Soccer Bowl", NULL, "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("64", "Canada", "[[Toronto]]", "2010 G-20 Toronto summit", NULL, "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("65", "Canada", "1", "Canada Cup", NULL, "2009");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("66", "USA", "[[Columbia", "Roots N Blues N BBQ Festival", NULL, "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("67", "China", "[[Fuzhou", "Fuzhou derailment", NULL, "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("68", "Mexico", NULL, "IIHF World Championship Division III", NULL, "2005");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("69", "Canada", NULL, "Canada Cup", NULL, "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("70", "India", "[[Sainthia]]", "Sainthia train collision", NULL, "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("71", "China", "Nanjing No.4 Plastics factory (abandoned) [[Qixia District]]", "2010 Nanjing chemical plant explosion", NULL, "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("72", "China", "Aksu", "2010 Aksu bombing", NULL, "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("73", "South Africa", "1", "IIHF World Championship Division III", NULL, "2011");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("74", "India", NULL, "[[List of Chief Ministers of Bihar", NULL, "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("75", "Canada", "6", "FIFA Women's World Cup", NULL, "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("76", "India", "Varanasi", "2010 Varanasi bombing", NULL, "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("77", "India", "[[Ajmer]]", "Ajmer Sharif Dargah blast", NULL, "2007");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("78", "South Africa", "", "African Nations Championship", NULL, "2014");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("79", "Canada", "[[Downsview Park]] [[Toronto]]", "Heavy T.O.", NULL, "2012");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("80", "Canada", NULL, "[[Prime Minister of Canada", NULL, "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("81", "Egypt", "[[Imbaba]]", "2011 Imbaba church attacks", NULL, "2011");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("82", "Mexico", "[[Mexico]]", "2011 Mexican Fire Season", NULL, "2011");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("83", "Canada", "1", NULL, NULL, "2007");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("84", "Mexico", "[[Arizona]]/[[New Mexico]]", "Wallow Fire", NULL, "2011");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("85", "Mexico", "[[New Mexico]]", "Las Conchas Fire", NULL, "2011");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("86", "China", "[[Kashgar]]", "2011 Kashgar attacks", NULL, "2011");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("87", "India", "[[Agra]]", "2011 Agra bombing", NULL, "2011");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("88", "Mexico", "Cuidad Juarez", "Murder of Luis Carlos Santiago", NULL, "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("89", "Canada", "2", "IIHF World Junior Championship", NULL, "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("90", "Brazil", "1", "Pan American Handball Men's Youth Championship", NULL, "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("91", "Brazil", "1", "Pan American Handball Women's Youth Championship", NULL, "2006");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("92", "Brazil", "1", "Pan American Handball Women's Youth Championship", NULL, "2007");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("93", "Brazil", "1", "Pan American Handball Women's Youth Championship", NULL, "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("94", "India", "[[Kozhikode]]", NULL, NULL, "2012");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("95", "China", NULL, "", NULL, "2012");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("96", "South Africa", "[[Durban]]", "5th BRICS Summit", NULL, "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("97", "Brazil", "1", "Pan American Handball Men's Youth Championship", NULL, "2006");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("98", "Mexico", "[[AtizapÃ¡n de Zaragoza]]", "Monterrey Tech bombing", NULL, "2011");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("99", "Mexico", "[[Nuevo Laredo]]", "2012 Nuevo Laredo massacres", NULL, "2012");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("100", "South Africa", "Cape Town", "Cape Town International Challenge", NULL, "2012");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("101", "South Africa", "2", "IIHF World Championship Division III", NULL, "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("102", "India", "[[M. Chinnaswamy Stadium]] [[Bangalore]]", "2010 Bangalore stadium bombing", NULL, "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("103", "Mexico", "[[Gila National Forest]]", "Whitewater-Baldy Complex Fire", NULL, "2012");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("104", "India", "Penukonda", "Penukonda train collision", NULL, "2012");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("105", "Canada", "[[Montreal]]", "2012 Montreal shooting", NULL, "2012");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("106", "India", "[[Kochi]]", "Emerging Kerala", NULL, "2012");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("107", "Mexico", "Boca Del RÃ­o", "2012 Veracruz murder of journalists", NULL, "2012");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("108", "South Africa", "1", "SAIHA Senior Club Championship", NULL, "2012");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("109", "Mexico", "Mexico City", "Homeless World Cup", NULL, "2012");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("110", "Brazil", "", "Torneio Internacional Cidade de SÃ£o Paulo de Futebol Feminino", NULL, "2011");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("111", "Brazil", "", "Torneio Internacional Cidade de SÃ£o Paulo de Futebol Feminino", NULL, "2010");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("112", "Brazil", "", "Torneio Internacional Cidade de SÃ£o Paulo de Futebol Feminino", NULL, "2009");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("113", "Canada", "2", "IIHF World Junior Championship", NULL, "2017");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("114", "China", "[[Yongchuan]]", "Four Nations Tournament", NULL, "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("115", "Egypt", "[[Giza Governorate]]", "Badrashin railway accident", NULL, "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("116", "India", "[[Dilsukhnagar]]", "2013 Hyderabad bombings", NULL, "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("117", "India", "[[Malleswaram]]", "2013 Bangalore blast", NULL, "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("118", "Canada", "[[Quebec]]", "2013 VIA Rail Canada terrorism plot", NULL, "2012");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("119", "India", "[[West Lafayette", "2008 NCAA Division I Men's Golf Championship", NULL, "2008");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("120", "India", "[[Srinagar]]", "June 2013 Srinagar attack", NULL, "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("121", "South Africa", "1", "SAIHA Junior Interprovincial Championship", NULL, "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("122", "Canada", "[[Sydney", "World U-17 Hockey Challenge", NULL, "2014");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("123", "Egypt", "[[Cairo]]", "August 2013 Cairo sit-ins dispersal", NULL, "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("124", "India", "[[Chennai]]", NULL, NULL, "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("125", "Brazil", "", "Grand Prix de Futsal", NULL, "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("126", "India", "[[Patna Junction]] Multiple locations at [[Gandhi Maidan Marg]]", "''2013 Patna Serial Blasts''", NULL, "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("127", "Canada", "1", NULL, NULL, "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("128", "Mexico", "1", "Pan American Ice Hockey Tournament", NULL, "2014");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("129", "India", "[[Chennai Central railway station]]", "Train Bombing", NULL, "2014");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("130", "China", "[[ÃrÃ¼mqi]]", "April 2014 ÃrÃ¼mqi attack", NULL, "2014");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("131", "China", "[[Guangzhou]]", "2014 Guangzhou attack", NULL, "2014");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("132", "China", "Gongyuan Street", "May 2014 ÃrÃ¼mqi attack", NULL, "2014");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("133", "India", "Bangalore", "India Inclusion Summit", NULL, "2013");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("134", "Canada", "[[Northwest Territories]]", "2014 Northwest Territories fires", NULL, "2014");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("135", "China", "Kunshan Zhongrong Metal Products Co.", "2014 Kunshan explosion", NULL, "2014");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("136", "Canada", "18", "[[International Champions Cup]]", NULL, "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("137", "Canada", "1", "Ball Hockey World Championship", NULL, "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("138", "Canada", "[[Ottawa]]", "2015 Ottawa Larmond twins terror conspiracy", NULL, "2014");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("139", "USA", "", "CONCACAF Men's Olympic Qualifying Championship", NULL, "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("140", "USA", "9", NULL, NULL, "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("141", "Brazil", "[[Americana", "Pan- American Korfball Championship", NULL, "2014");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("142", "South Africa", "[[Cape Town]]", NULL, NULL, "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("143", "Brazil", "1", "Pan American Men's Club Handball Championship", NULL, "2014");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("144", "China", "Republics of [[Khakassia]] and [[Zabaykalsky Krai]]", "2015 Russian wildfires<!--This must be the same name as the article. Do not change unless the article is moved.-->", NULL, "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("145", "South Africa", "[[Durban]] [[Johannesburg]] [[South Africa]]", "Durban Xenophobic attack 2015", NULL, "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("146", "South Africa", "Denver station", "Denver train crash", NULL, "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("147", "Canada", "1", "IIHF World Championship", NULL, "2016");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("148", "Mexico", "1", "Pan American Ice Hockey Tournament", NULL, "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("149", "USA", "[[Newport", NULL, NULL, "2016");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("150", "China", "[[Xiamen]]", "World University Football Cup", NULL, "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("151", "India", "[[Srinagar]]", NULL, NULL, "2015");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("152", "Mexico", "1", "IIHF U20 World Championship Division III", NULL, "2016");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("153", "India", "[[National Capital Region (India)]]", "<!-- Title to display, if other than page name -->", NULL, "2016");
INSERT INTO event (event_key, event_location_country, specific_location, name, attendance, date) VALUES ("154", "India", "[[Chennai]]", NULL, NULL, "2016");
